services:
  - type: web
    name: etnamonitor-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: DATA_DIR
        value: /data
      - key: LOG_DIR
        value: /data/log
      - key: CSV_PATH
        value: /data/curva.csv
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: TELEGRAM_BOT_MODE
        value: off
  - type: worker
    name: etnamonitor-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker_telegram_bot.py
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
